### ISSUE TITLE
Is there a user-defined litteral for minutes ?

### ISSUE THREAD

**Issue by chavid** [martinmoene/PhysUnits-CT-Cpp11#13]
Hi.
I was wondering how to express something like `quantity<time_interval_d> d { 39_minutes } ;`.
Browsing the source code, I got the feeling you implemented all the 10 multiples for user-defined litterals, but not the 60 multiples for the time units.
Is there some more detailed documentation than the README.md ?
++

**Comment by martinmoene** [comment]
Hi @chavid , thanks for pointing out this omission. Currently there's no documentation apart from the Readme.

I'll add literals `_min`, `_hour` and `_day`.

**Comment by chavid** [comment]
👍

**Comment by martinmoene** [comment]
I'm closing this issue, please reopen if it's premature.
