### ISSUE TITLE
Add Au to alternatives section

### ISSUE THREAD

**Issue by chiphogg** [martinmoene/PhysUnits-CT-Cpp11#17]
Thanks for maintaining your list of C++ units libraries!  It's a really useful resource.

Today, we released our open source units library (Au), which can be found here (https://github.com/aurora-opensource/au).  I think the summary is apt:

> A C++14-compatible physical units library with no dependencies and a single-file delivery option. Emphasis on safety, accessibility, performance, and developer experience.

Could Au please be added to the list in your README?

**Comment by martinmoene** [comment]
Thanks for the heads-up, I'll add _Au_ to to the list with pleasure.

**Comment by chiphogg** [comment]
Thanks so much!  I really appreciate it.
