### ISSUE TITLE
Product<...>::dimension_type for dimensionless result

### ISSUE THREAD

**Issue by mreininghaus** [martinmoene/PhysUnits-CT-Cpp11#7]
I am currently trying to implement vectors of quantities with corresponding arithmetic operations and am facing an issue when multiplying quantities with inverse dimensions, i.e. the result being dimensionless. In this case, using ``phys::units::detail::Product<dim1, dim2, double, double>::dimension_type`` does not work (with ``dim1`` and ``dim2`` being inverse) to deduce the resulting dimension.

Here is a MWE (C++14):
```
#include <phys/units/quantity.hpp>
#include <phys/units/io.hpp>
#include <iostream>

template <typename dim>
struct QuantityContainer // keeps a quantity inside, a tuple of them in real life
{
    using Quantity = phys::units::quantity<dim, double>;
    
    double raw_value;
    
    QuantityContainer(double a) : raw_value(a) {}
    QuantityContainer(Quantity a) : raw_value(a.magnitude()) {}
    
    template <typename ScalarDim>
    auto operator*(phys::units::quantity<ScalarDim, double> const p) const
    {
        return QuantityContainer<typename phys::units::detail::Product<ScalarDim, dim, double, double>::dimension_type>(raw_value * p.magnitude());
    }
    
    auto operator*(double const p) const
    {
        return QuantityContainer<dim>(raw_value * p);
    }
};


template <typename dim>
auto& operator<<(std::ostream& os, QuantityContainer<dim> qc)
{
    using Quantity = phys::units::quantity<dim, double>;
    
    os << qc.raw_value << " " << phys::units::to_unit_symbol<dim, double>(Quantity(phys::units::detail::magnitude_tag, 1));
    return os;
}


int main()
{
    using namespace phys::units; 
    using namespace phys::units::literals;

    QuantityContainer<length_d> l(3_m);
    
    auto b = l * 2; // still a length
    auto c = l * 2_s; // length * time, works fine
    
    std::cout << l << std::endl;
    std::cout << b << std::endl;
    std::cout << c << std::endl;
    
    auto d = l * (1 / 2_m); // length / length = dimensionless, compiler error
    std::cout << d << std::endl;
    
    return 0;
}

```
The error can be traced back to ``collapse< dimensionless_d, T >`` and the fact that ``is_all_zero``-quantities are cast to plain old doubles.

As a workaround, I assume I could use whole quantities as template parameter instead of only the dimension but I still have the feeling it should be possible this way somehow, if possible without a template specialization covering the ``dimensionless_d`` case.

**Comment by martinmoene** [comment]
For what reason would you prefer to use a vector of non-quantity over a vector of quantity?

**Comment by mreininghaus** [comment]
To be able to use vectors from Eigen as underlying container.

**Comment by martinmoene** [comment]
Ah. What is the compilation error?

I'm not near a computer of usable size for a few weeks, making it difficult to be of (much) help.

**Comment by martinmoene** [comment]
Not sure how important it is to you to use this C++11 PhysUnits library.

A good alternative may be Nick Holthaus' C++14 [units library](https://github.com/nholthaus/units) as it is better documented and is being actively maintained.

**Comment by martinmoene** [comment]
Further, I'm wondering if it makes sense to be able to omit the collapse-to-double (via configuration) and continue computations with `quantity<dimensionless_d, double>`.

**Comment by martinmoene** [comment]
@mreininghaus is this issue still relevant to you?

**Comment by mreininghaus** [comment]
After some experiments I found a rather simple way to deal with the issue using a `if constexpr`:
```C++
template <typename ScalarDim>
auto operator*(phys::units::quantity<ScalarDim, double> const p) const
{
    using ProdQuantity = phys::units::detail::Product<ScalarDim, dim, double, double>;

    if constexpr (std::is_same<ProdQuantity, double>::value)
        // here, there is no ProdQuantity::dimension_type since ProdQuantity collapsed to double
        return QuantityContainer<phys::units::dimensionless_d>(raw_value * p.magnitude());
    else
        // here, ProdQuantity::dimension_type is defined
        return QuantityContainer<typename ProdQuantity::dimension_type>(raw_value * p.magnitude());
}
```
In addition, I had to remove the `static_assert( has_dimension, "quantity dimensions must not all be zero" )` from PhysUnits that prevents instantiating dimensionless quantities.

Thank you for suggesting nholthaus/units. It looks quite promising and I'll give it a shot. I actually sticked to your library so far simply because it was the first one I found supporting all the features I wanted.

**Comment by martinmoene** [comment]
Ok, thanks for your information. 

I'll make the collapsing of dimensionless quantities to double configurable, see issue #8.

P.s.: however not within the next two weeks.

**Comment by mreininghaus** [comment]
Works perfectly for me now, thanks!

**Comment by martinmoene** [comment]
Thanks for letting me know!
